# Generated by Django 4.1.8 on 2023-05-09 23:15

import ckeditor.fields
from django.db import migrations, models

import videos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("html_id", models.CharField(max_length=20, verbose_name="HTML id")),
                ("lat", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_shot", models.DateField(verbose_name="Date taken")),
                (
                    "poster",
                    models.FileField(
                        upload_to="poster/%Y/%m/",
                        validators=[videos.validators.validate_poster_extension],
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="video/%Y/%m/",
                        validators=[videos.validators.validate_video_extension],
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "rich_description",
                    ckeditor.fields.RichTextField(blank=True, default="", null=True),
                ),
                ("lat", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, default=None, to="videos.tag"),
                ),
            ],
            options={"ordering": ["-date_shot"],},
        ),
        migrations.CreateModel(
            name="ExternalVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_shot", models.DateField(verbose_name="Date taken")),
                ("embed_code", models.TextField(blank=True, default=None, null=True)),
                ("poster", models.FileField(upload_to="poster/%Y/%m/")),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "rich_description",
                    ckeditor.fields.RichTextField(blank=True, default="", null=True),
                ),
                ("lat", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, default=None, to="videos.tag"),
                ),
            ],
            options={"ordering": ["-date_shot"],},
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("poster", models.FileField(upload_to="poster/%Y/%m/")),
                (
                    "external_videos",
                    models.ManyToManyField(
                        blank=True, default=None, to="videos.externalvideo"
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(blank=True, default=None, to="videos.video"),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
