# Generated by Django 4.1.8 on 2023-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capitals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="photo", name="photo_height",),
        migrations.RemoveField(model_name="photo", name="photo_width",),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.ImageField(upload_to="flags/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_file",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
