# Generated by Django 4.1.8 on 2023-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capitals", "0003_remove_photo_is_capitol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.FileField(upload_to="flags/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_file",
            field=models.FileField(upload_to="photos/"),
        ),
    ]
