# Generated by Django 4.1.10 on 2023-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capitals", "0006_photo_photo_height_photo_photo_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo_height",
            field=models.IntegerField(blank=True, verbose_name="Height (auto-calc)"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_width",
            field=models.IntegerField(blank=True, verbose_name="Width (auto-calc)"),
        ),
    ]
