# Generated by Django 4.1.8 on 2023-05-09 19:54

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("reading_date", models.DateField()),
                ("odometer_reading", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Car Miles", "ordering": ["reading_date"],},
        ),
        migrations.CreateModel(
            name="Electricity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("service_start_date", models.DateField()),
                ("service_end_date", models.DateField()),
                ("kWh_usage", models.IntegerField(verbose_name="Grid Energy Consumed")),
                (
                    "solar_amt_sent_to_grid",
                    models.IntegerField(verbose_name="Solar Sent to Grid"),
                ),
                (
                    "net_metering_credit",
                    models.IntegerField(default=0, verbose_name="Net Metering Balance"),
                ),
                (
                    "energy_charge_per_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=Decimal("0.11815"),
                        max_digits=9,
                        null=True,
                        verbose_name="Energy Charge per kWh",
                    ),
                ),
                (
                    "storm_recover_cost_per_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=Decimal("0.00219"),
                        max_digits=9,
                        null=True,
                        verbose_name="Storm Recovery Cost per kWh",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Electricity",
                "ordering": ["service_start_date"],
            },
        ),
        migrations.CreateModel(
            name="Gas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("service_start_date", models.DateField()),
                ("service_end_date", models.DateField()),
                ("therms_usage", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Natural Gas",
                "ordering": ["service_start_date"],
            },
        ),
        migrations.CreateModel(
            name="SolarEnergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("date_of_production", models.DateField()),
                ("production", models.IntegerField(verbose_name="Watts produced")),
            ],
            options={
                "verbose_name_plural": "Solar Energy",
                "ordering": ["date_of_production"],
            },
        ),
        migrations.CreateModel(
            name="Water",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("service_start_date", models.DateField()),
                ("service_end_date", models.DateField()),
                (
                    "avg_gallons_per_day",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "verbose_name_plural": "Water",
                "ordering": ["service_start_date"],
            },
        ),
    ]
