# Generated by Django 4.1.10 on 2024-11-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('app_code', models.CharField(max_length=200)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('issued_datetime', models.DateTimeField(auto_now=True)),
                ('expires_in', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CarMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('reading_date', models.DateField()),
                ('odometer_reading', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Car Miles',
                'ordering': ['reading_date'],
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('kWh_usage', models.IntegerField(verbose_name='Energy Used (Grid Energy Consumed)')),
                ('solar_amt_sent_to_grid', models.IntegerField(verbose_name='Energy Delivered to Grid (Solar Sent to Grid)')),
                ('net_metering_credit', models.IntegerField(default=0, verbose_name='Carried Forward Balance')),
                ('calculated_money_saved_by_solar', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Calc $$ Saved')),
            ],
            options={
                'verbose_name_plural': 'Electricity',
                'ordering': ['service_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('therms_usage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Natural Gas',
                'ordering': ['service_start_date'],
            },
        ),
        migrations.CreateModel(
            name='SolarEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('date_of_production', models.DateField()),
                ('production', models.IntegerField(verbose_name='Watts produced')),
            ],
            options={
                'verbose_name_plural': 'Solar Energy',
                'ordering': ['date_of_production'],
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('avg_gallons_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Water',
                'ordering': ['service_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectricRateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date_perpetual', models.BooleanField(default=False)),
                ('energy_charge_per_kwh', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True, verbose_name='Charge per kWh')),
                ('electricity_bills', models.ManyToManyField(blank=True, to='data.electricity')),
            ],
            options={
                'verbose_name_plural': 'Electricity Rate Schedules',
                'ordering': ['name'],
            },
        ),
    ]
