# Generated by Django 4.1.8 on 2023-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_electricrateschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricity",
            name="energy_charge_per_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=9,
                null=True,
                verbose_name="Energy Charge per kWh",
            ),
        ),
        migrations.AddField(
            model_name="electricity",
            name="storm_recover_cost_per_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=9,
                null=True,
                verbose_name="Storm Recovery Cost per kWh",
            ),
        ),
    ]
