# Generated by Django 5.1.2 on 2025-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_app_authtoken_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='electricity_pdfs/', verbose_name='Uploaded PDF Bill'),
        ),
    ]
