# Generated by Django 5.1.10 on 2025-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_electricity_uploaded_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='gas_pdfs/', verbose_name='Uploaded PDF Bill'),
        ),
        migrations.AddField(
            model_name='water',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='water_pdfs/', verbose_name='Uploaded PDF Bill'),
        ),
    ]
