# Generated by Django 4.1.8 on 2023-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_electricity_energy_charge_per_kwh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricrateschedule",
            name="comments",
            field=models.CharField(default="comment", max_length=200),
            preserve_default=False,
        ),
    ]
