# Generated by Django 4.1.8 on 2023-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_electricity_calculated_money_saved_by_solar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricity",
            name="calculated_money_saved_by_solar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Calc $$ Saved",
            ),
        ),
    ]
