# Generated by Django 4.1.10 on 2023-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_alter_electricity_calculated_money_saved_by_solar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricRateSchedule2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("submit_date", models.DateField(auto_now_add=True)),
                ("comments", models.CharField(max_length=200)),
                ("schedule_start_date", models.DateField()),
                ("schedule_end_date", models.DateField()),
                (
                    "energy_charge_per_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=9,
                        null=True,
                        verbose_name="Charge per kWh",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Electricity Rate Schedules",
                "ordering": ["schedule_start_date"],
            },
        ),
    ]
