# Generated by Django 4.1.10 on 2023-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_electricrateschedule2_electricity_bills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricrateschedule2",
            name="comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
