# Generated by Django 4.1.10 on 2023-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_alter_electricrateschedule2_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricrateschedule2",
            name="electricity_bills",
            field=models.ManyToManyField(blank=True, to="data.electricity"),
        ),
    ]
