# Generated by Django 4.1.10 on 2023-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_alter_electricrateschedule2_electricity_bills"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricrateschedule2",
            name="elec_bills_schedule",
            field=models.BooleanField(default=False),
        ),
    ]
