# Generated by Django 4.1.10 on 2023-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_remove_electricrateschedule2_elec_bills_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricrateschedule2",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Electricity Rate Schedules",
            },
        ),
        migrations.AlterField(
            model_name="electricrateschedule2",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
