# Generated by Django 4.1.10 on 2023-08-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0014_alter_electricrateschedule2_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ElectricRateSchedule",),
    ]
