# Generated by Django 4.1.10 on 2023-08-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_electricrateschedule_delete_electricrateschedule2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ElectricRateSchedule", new_name="ElectricRateSchedule2",
        ),
    ]
