# Generated by Django 4.1.10 on 2023-08-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_rename_electricrateschedule2_electricrateschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricrateschedule",
            name="submit_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
