# Generated by Django 4.1.10 on 2023-08-22 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_alter_electricrateschedule_submit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricrateschedule",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="electricrateschedule",
            name="submit_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
