# Generated by Django 4.1.10 on 2023-08-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_alter_electricrateschedule_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricrateschedule",
            name="energy_charge_per_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=9,
                null=True,
                verbose_name="Charge per kWh",
            ),
        ),
    ]
