# Generated by Django 4.1.10 on 2024-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_alter_authtoken_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="expires_in",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="issued_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
