# Generated by Django 4.1.10 on 2024-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_authtoken_expires_in_authtoken_issued_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="app_code",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authtoken",
            name="client_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authtoken",
            name="client_secret",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authtoken",
            name="redirect_uri",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electricity",
            name="kWh_usage",
            field=models.IntegerField(
                verbose_name="Energy Used (Grid Energy Consumed)"
            ),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="solar_amt_sent_to_grid",
            field=models.IntegerField(
                verbose_name="Energy Delivered to Grid (Solar Sent to Grid)"
            ),
        ),
    ]
