# Generated by Django 4.1.10 on 2024-10-24 16:46

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": [
                    django.db.models.functions.comparison.Coalesce(
                        "sort_title", "title"
                    )
                ]
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="sort_title",
            field=models.CharField(
                blank=True,
                default=models.CharField(max_length=300),
                max_length=300,
                null=True,
            ),
        ),
    ]
