# Generated by Django 4.1.10 on 2024-11-23 14:59

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_movie_sort_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': [django.db.models.functions.comparison.Coalesce(models.Case(models.When(sort_title='', then=None), default='sort_title', output_field=models.CharField()), 'title')]},
        ),
    ]
